version: "3.9"
services:
  api:
    build: .
    image: ${DOCKERHUB_USERNAME:-yourname}/node-express-api:dev
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
    restart: unless-stopped