replicaCount: 2

image:
  repository: yourname/node-express-api
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 4000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "4000"

livenessProbe:
  httpGet:
    path: /
    port: 4000
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 4000
  initialDelaySeconds: 5
  periodSeconds: 10